version: 2

models:
  - name: fact_water_quality_data
    columns:
      - name: state_well_number
        date_type: text
        data_tests:
          - not_null
      - name: sample_id
        date_type: text
      - name: sample_date
        date_type: date
        data_tests:
          - not_null
      - name: test_method
        date_type: text
      - name: lab
        date_type: text
      - name: analyte
        date_type: text
        data_tests:
          - not_null
      - name: raw_lab_result
        date_type: text
      - name: quantitative_result
        date_type: real
      - name: units
        date_type: text
      - name: maximum_contaminant_limit
        date_type: text
      - name: lab_comment
        date_type: text

  - name: fact_historical_water_levels
    description: Historical water levels
    columns:
      - name: state_well_number
        description: The primary key for this table
        data_type: text
        data_tests:
          - not_null
      - name: reading_date
        description: Date when level was read
        data_type: date
      - name: ground_level
        description: Measured in feet
        data_type: real
      - name: depth_to_water
        description: Depth of water in feet
        data_type: real
      - name: ground_water_elevetion
        description: Ground level - depth to water, measured in feet
        data_type: real
