version: 2

models:
  - name: fact_water_quality_data
    columns:
      - name: state_well_number
        data_type: text
        data_tests:
          - not_null
      - name: sample_id
        data_type: text
        description: ID of sample (provided and used by Lab)
      - name: sample_date
        data_type: date
        description: Date water was sampled
        data_tests:
          - not_null
      - name: test_method
        data_type: text
        description: Method used to test sample for analyte
      - name: lab
        data_type: text
        description: Lab that conducted the test
      - name: analyte
        data_type: text
        description: Consituent (organic, metal, etc) tested for
        data_tests:
          - not_null
      - name: raw_lab_result
        data_type: text
        description: Result as provided by lab (contains mixed type)
      - name: quantitative_result
        data_type: real
        description: Numerical results casted into corrected type
      - name: units
        data_type: text
        description: Unit of measurement used, different for each analyte
      - name: min_detectable_limit
        data_type: real
        description: Minimum amount of analyte detectable in sample
      - name: maximum_contaminant_limit
        data_type: real
        description: Maximum amount of analyte allowed in sample to be allowed for consumption

  - name: fact_historical_water_levels
    description: Historical water levels
    columns:
      - name: state_well_number
        data_type: text
        data_tests:
          - not_null
      - name: reading_date
        description: Date when level was read
        data_type: date
      - name: ground_level
        description: Feet above sea level, measured in feet
        data_type: real
      - name: depth_to_water
        description: Depth of water from wellhead, measured in feet
        data_type: real
      - name: ground_water_elevetion
        description: Ground level - depth to water, measured in feet
        data_type: real

  - name: monthly_grazing
    columns:
      - name: grazer
        description: name of grazing company
        data_type: text
      - name: reporting_date
        description: date which grazing numbers were reported from Jim Jones
        data_type: date
      - name: area
        description: area of KWB in which animals grazed
        data_type: text
      - name: number_of_animal_units
        description: count of grazing animals in area for given time period
        data_type: int
      - name: comments
        description: comment given by grazer on operations for given area at given time
        data_type: text

  - name: rolling_twelve_month_grazing_totals
    columns:
      - name: reporting_date
        description: date of reporting; days within a one week lag are wrapped up into this date
        data_type: date
      - name: total
        description: number of grazing animals on property for given date, regardless of area/grazer
        data_type: number
  - name: fact_rainfall
    columns:
      - name: gaugeid
        description: well number used to identify location of rain gauge
        data_type: text
        data_tests:
          - not_null
      - name: reading_date
        description: date on which reading was done
        data_type: date
        data_tests:
          - not_null
      - name: measurement
        description: measured in inches
        data_type: real
        data_tests:
          - not_null
    description: "fact table showing rainfall data gathered from two sources: historically from a field maps app going from 2015 to 3/13/2025, and currently from a survey123 survey from 3/13/2025 - today."
  - name: water_year_rainfall
    description: aggregate view showing total rainfall in water year (oct-sep) per gauge
    columns:
      - name: gaugeid
        description: well number associated with gauge location
        data_type: text
      - name: water_year_total
        description: sum of rainfall in water year, units are inches
        data_type: numeric
  - name: water_year
    description: calendar of dates for a given water year. These run from October to September and the year number is the one it ends on. So for 2025 the water year would be October 1, 2024 to September 30, 2025
    columns:
      - name: water_calendar_date
        description: date in water year
        data_type: date
