version: 2

models:
  - name: fact_monitoring_water_levels
    description: Historical water levels
    columns:
      - name: state_well_number
        data_type: text
        data_tests:
          - not_null
      - name: reading_date
        description: Date when level was read
        data_type: date
      - name: ground_level
        description: Feet above sea level, measured in feet
        data_type: real
      - name: depth_to_water
        description: Depth of water from wellhead, measured in feet
        data_type: real
      - name: ground_water_elevetion
        description: Ground level - depth to water, measured in feet
        data_type: real

  - name: monthly_grazing
    columns:
      - name: grazer
        description: name of grazing company
        data_type: text
      - name: reporting_date
        description: date which grazing numbers were reported from Jim Jones
        data_type: date
      - name: area
        description: area of KWB in which animals grazed
        data_type: text
      - name: number_of_animal_units
        description: count of grazing animals in area for given time period
        data_type: int
      - name: comments
        description: comment given by grazer on operations for given area at given time
        data_type: text

  - name: rolling_twelve_month_grazing_totals
    columns:
      - name: reporting_date
        description: date of reporting; days within a one week lag are wrapped up into this date
        data_type: date
      - name: total
        description: number of grazing animals on property for given date, regardless of area/grazer
        data_type: number
  - name: fact_rainfall_measurements
    columns:
      - name: gaugeid
        description: well number used to identify location of rain gauge
        data_type: text
        data_tests:
          - not_null
      - name: reading_date
        description: date on which reading was done
        data_type: date
        data_tests:
          - not_null
      - name: measurement
        description: measured in inches
        data_type: real
        data_tests:
          - not_null
    description: "fact table showing rainfall data gathered from two sources: historically from a field maps app going from 2015 to 3/13/2025, and currently from a survey123 survey from 3/13/2025 - today."
  - name: water_year_rainfall
    description: aggregate view showing total rainfall in water year (oct-sep) per gauge
    columns:
      - name: gaugeid
        description: well number associated with gauge location
        data_type: text
      - name: water_year_total
        description: sum of rainfall in water year, units are inches
        data_type: numeric
  - name: water_year
    description: calendar of dates for a given water year. These run from October to September and the year number is the one it ends on. So for 2025 the water year would be October 1, 2024 to September 30, 2025
    columns:
      - name: water_calendar_date
        description: date in water year
        data_type: date
  - name: stg_historical_sems_gw_levels_pre_2020
    description: Staging table for historical gw water levels pre-2019.
    columns:
      - name: state_well_number
        description: state well number
        data_type: text
      - name: reading_date
        description: date measurement was taken
        data_type: date
      - name: depth_to_water
        description: depth to ground water from top of well.
        data_type: real
      - name: source
        description: "Since this data comes from the KCWA database SEMS, this is set to SEMS (note: SEMS is probably sunsetted by 2026)."
        data_type: text
  - name: stg_metro_gw_levels_post_2020
    description: Staging table for historical gw water levels post 2020 coming from metro.
    columns:
      - name: state_well_number
        description: state well number
        data_type: text
      - name: reading_date
        description: date measurement was taken
        data_type: date
      - name: depth_to_water
        description: depth to ground water from top of well.
        data_type: real
      - name: source
        description: Since this data comes from the Metro, this is set to Metro.
        data_type: text
  - name: stg_bsk_lab_results
    description: Staging table for lab resulst from BSK.
    columns:
      - name: state_well_number
        data_type: text
      - name: sample_id
        data_type: text
      - name: sample_date
        data_type: date
      - name: analysis_method
        data_type: text
      - name: lab
        data_type: text
      - name: analyte
        data_type: text
      - name: result
        data_type: text
      - name: units
        data_type: text
      - name: min_detectable_limit
        data_type: real
      - name: max_report_limit
        data_type: real
  - name: stg_historical_eurofins_results_from_pdfs
    description: Staging table for historical lab results from Eurofins, extracted from pdfs using OCR.
    columns:
      - name: state_well_number
        data_type: text
      - name: sample_id
        data_type: text
      - name: sample_date
        data_type: date
      - name: analysis_method
        data_type: text
      - name: lab
        data_type: text
      - name: analyte
        data_type: text
      - name: result
        data_type: text
      - name: units
        data_type: text
      - name: min_detectable_limit
        data_type: real
      - name: max_report_limit
        data_type: real
  - name: stg_historical_lab_results
    description: Staging table for historical lab results compiled in Excel back in 2023. There is some overlap with the eurofins table but this is accounted for via deduping.
    columns:
      - name: state_well_number
        data_type: text
      - name: sample_id
        data_type: text
      - name: sample_date
        data_type: date
      - name: analysis_method
        data_type: text
      - name: lab
        data_type: text
      - name: analyte
        data_type: text
      - name: result
        data_type: text
      - name: units
        data_type: text
      - name: min_detectable_limit
        data_type: real
      - name: max_report_limit
        data_type: real
  - name: stg_historical_ext_readings
    description: Staging for historical extensometer readings. One day per month per reading
    columns:
      - name: reading_date
        description: date of extensometer reading
        data_type: date
      - name: measurement
        description: net change in elevation (ft)
        data_type: real
  - name: stg_fact_ext_readings
    description: Staging table for extensometer readings, provided by DWR via HydroVu
    columns:
      - name: reading_timestamp
        data_type: timestamp without time zone
      - name: measurement
        data_type: real
      - name: reading_date
        description: date readings were collected
        data_type: date
        data_tests:
          - not_null
      - name: daily_average_measurement
        description: average daily measurements of net change
        data_type: numeric
        data_tests:
          - not_null
  - name: fact_extensometer_readings
    description: combined table showing historical extensometer data with HyrdoVu provided data
    columns:
      - name: reading_date
        description: date of readings
        data_type: date
      - name: measurement
        description: daily averages of changes in elevation (ft)
        data_type: real
  - name: fact_water_quality_test_results
    description: Lab results from both monitoring and recovery wells on KWB property
    columns:
      - name: state_well_number
        description: Unique identifier of well
        data_type: text
        data_tests:
          - not_null
      - name: sample_date
        description: Date water was sampled
        data_type: date
        data_tests:
          - not_null
      - name: sample_time
        description: Time on date water was sampled
        data_type: time without time zone
      - name: lab
        description: Lab that conducted the test
        data_type: text
      - name: lab_sample_id
        description: id of sample, given by lab
        data_type: text
      - name: analyte
        description: Consituent (organic, metal, etc) tested for
        data_type: text
        data_tests:
          - not_null
      - name: qualifier
        description: Some results are described as being above or below an amount, using "<" or ">". This captures that feature.
        data_type: text
      - name: result
        description: quantitative result of lab test
        data_type: real
      - name: qualitative_result
        description: qualitative result, either "ND" if not detected or actually qualitative such as "No odor detected"
        data_type: text
      - name: units
        description: Unit of measurement used, different for each analyte
        data_type: text
      - name: minimum_reportable_limit
        description: Minimum limit at which result must be reported.
        data_type: real
