version: 2

sources:
  - name: agol
    database: kwb  
    schema: agol  
    tables:
        - name: wells
          columns:
            - name: id
              data_type: bigint
            - name: date_added
              data_type: timestamp without time zone
            - name: state_well_num
              data_type: text
            - name: permit_num
              data_type: text
            - name: year_built
              data_type: integer
            - name: well_type
              data_type: text
            - name: status
              data_type: text
            - name: lat
              data_type: real
            - name: lon
              data_type: real
            - name: township
              data_type: text
            - name: range
              data_type: text
            - name: section
              data_type: integer
            - name: ground_level
              data_type: real
            - name: total_depth
              data_type: real
            - name: bowl_depth
              data_type: real
            - name: top_screen
              data_type: real
            - name: bottom_screen
              data_type: real
            - name: casing_diameter
              data_type: real
            - name: motor_hp
              data_type: real
            - name: testing_group
              data_type: text
            - name: notes
              data_type: text

        - name: fact_grazing
          columns:
            - name: grazer
              data_type: text
            - name: reporting_date
              data_type: date
            - name: area
              data_type: text
            - name: number_of_animal_units
              data_type: integer
            - name: comments
              data_type: text

        - name: fact_rainfall_survey
        - name: historic_field_maps_rainfall

  - name: grazing
    database: kwb  
    schema: grazing  
    tables:
        - name: fact_grazing
          columns:
            - name: grazer
              data_type: text
            - name: reporting_date
              data_type: date
            - name: area
              data_type: text
            - name: number_of_animal_units
              data_type: integer
            - name: comments
              data_type: text

  - name: water_quality
    database: kwb  
    schema: water_quality  
    tables:
        - name: historical_water_quality_lab_results
          columns:
            - name: state_well_number
              data_type: text
            - name: sample_id
              data_type: text
            - name: sample_date
              data_type: date
            - name: test_method
              data_type: text
            - name: lab
              data_type: text
            - name: analyte
              data_type: text
            - name: lab_result
              data_type: text
            - name: units
              data_type: text
            - name: maximum_contaminant_limit
              data_type: text
            - name: lab_comment
              data_type: text
        - name: bsk_lab_results
        - name: eurofins_lab_results_from_pdfs

  - name: kcwa
    database: kwb  
    schema: kcwa  
    tables:
        - name: historical_sems_water_levels_pre_2020
          columns:
            - name: state_well_number
              data_type: text
            - name: well_name
              data_type: text
            - name: mon_depth
              data_type: text
            - name: point_x
              data_type: real
            - name: point_y
              data_type: real
            - name: water_levels_read_date
              data_type: date
            - name: gwelev
              data_type: real
            - name: rpelev
              data_type: real
            - name: dtgw
              data_type: real
            - name: gselev
              data_type: real
            - name: rp_to_ws
              data_type: real

        - name: metro_water_levels_post_2020
          columns:
            - name: state_well_number
              data_type: text
            - name: reading_date
              data_type: date
            - name: depth_to_water
              data_type: real


